server:
  port: 8888
  servlet:
    context-path: /api

spring:
  profiles:
    active: local

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: off

logging:
  file:
    name: logs/toby-be
  logback:
    rollingpolicy:
      max-file-size: 10MB
  pattern:
    file: "%d [%t] %-5level %logger{36} - %msg%n"
#    console:
  level:
    org.springframework.web: ERROR
    org.springframework.security: DEBUG
    org.hibernate: ERROR
    tunght.toby.*: DEBUG

toby:
  auth:
    token:
      sign-key: signKey012345678901234567890123456789
      valid-time: 3600
  otp:
    valid-time: 180