server:
  port: 8882

spring:
  datasource:
    #    localhost 3306, docker 3307
    url: jdbc:mysql://localhost:3307/toby_me
    username: root
    password: lovecan148
  redis:
    database: 0
    password: 123456a@
    host: localhost
    port: 6379
    timeout: 60000

mail-sender:
  host: smtp.gmail.com
  port: 587
  email: tunghtopenai@gmail.com
  password: osxezajjnbtwsapj